# Generated by Django 5.0.1 on 2024-01-24 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cryptocurrency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cryptocurrency",
            options={"ordering": ["rank"], "verbose_name_plural": "Cryptocurrencies"},
        ),
    ]
